package edu.unimelb.jarvis.enums;

public enum MessageType {
    DRAWN,
    CHAT_MESSAGE,
    KICK_PARTICIPANT,
    CREATE_MANAGER,
    CREATE_PARTICIPANT,
    CREATE_PARTICIPANT_ACCEPTED,
    CREATE_PARTICIPANT_REJECTED,
    GET_ALL_WHITEBOARDS,
    GET_ALL_USERS,
    INIT_WHITEBOARD,
    NEW_WHITEBOARD,
    OPEN_WHITEBOARD,
    SAVE_WHITEBOARD,
    CLOSE_WHITEBOARD,
    SERVER_SHUTDOWN,
}
